# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agave_job', '0004_submission_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='result',
            field=models.NullBooleanField(),
        ),
    ]
